# Generated by Django 2.1 on 2019-04-18 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_transcription_workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranscript',
            fields=[
                ('transcriptID', models.IntegerField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('fileFormat', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('In Update Process', 'In Update Process')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTranscriptionVersion',
            fields=[
                ('versionNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('currentRole', models.CharField(choices=[('Initialization', 'Initialization'), ('Correction', 'Correction'), ('Finalization', 'Finalization')], max_length=30)),
                ('submittionDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('filePath', models.URLField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('In Update Process', 'In Update Process')], max_length=30)),
                ('transcriptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_transcription_workflow.VideoTranscript')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
