# Generated by Django 2.1 on 2019-04-18 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_transcription_workflow', '0002_auto_20190418_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscript',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='videotranscriptionversion',
            name='submittionDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
