# Generated by Django 2.1 on 2019-04-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transcription_workflow', '0003_auto_20190418_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscriptionversion',
            name='filePath',
            field=models.TextField(),
        ),
    ]
